/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
	},
	{
			displayName: 'Nacionalidade',
			name: 'nacionalidade',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'URL Externa',
			name: 'urlExterna',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Ambiente',
			name: 'ambiente',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Biometria FACE',
			name: 'biometriaFace',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Situacao CPF',
			name: 'situacaoCpf',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'DATA Nascimento',
			name: 'dataNascimento',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH Possui Impedimento',
			name: 'cnhPossuiImpedimento',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH Codigo Situacao',
			name: 'cnhCodigoSituacao',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH DATA Ultima Emissao',
			name: 'cnhDataUltimaEmissao',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH Registro Nacional Estrangeiro',
			name: 'cnhRegistroNacionalEstrangeiro',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH DATA Validade',
			name: 'cnhDataValidade',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH DATA Primeira Habilitacao',
			name: 'cnhDataPrimeiraHabilitacao',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH NUMERO Registro',
			name: 'cnhNumeroRegistro',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH Observacoes',
			name: 'cnhObservacoes',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CNH Categoria',
			name: 'cnhCategoria',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Endereco UF',
			name: 'enderecoUf',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Endereco Municipio',
			name: 'enderecoMunicipio',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Endereco CEP',
			name: 'enderecoCep',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Endereco Bairro',
			name: 'enderecoBairro',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Endereco Complemento',
			name: 'enderecoComplemento',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Endereco NUMERO',
			name: 'enderecoNumero',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Endereco Logradouro',
			name: 'enderecoLogradouro',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Documento UF Expedidor',
			name: 'documentoUfExpedidor',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Documento ORGAO Expedidor',
			name: 'documentoOrgaoExpedidor',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Documento NUMERO',
			name: 'documentoNumero',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Documento TIPO',
			name: 'documentoTipo',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Filiacao NOME PAI',
			name: 'filiacaoNomePai',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'Filiacao NOME MAE',
			name: 'filiacaoNomeMae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'SEXO',
			name: 'sexo',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'NOME',
			name: 'nome',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
		},
	{
			displayName: 'CPF',
			name: 'cpf',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['receita_federal'], operation: ['serpro_dv_face_tarifado'] } },
			required: true,
		},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = (this.getNodeParameter('webhookUrl', i) as string);
	const parametros: IDataObject = {
		'NACIONALIDADE': this.getNodeParameter('nacionalidade', i) as string,
		'URL_EXTERNA': this.getNodeParameter('urlExterna', i) as string,
		'AMBIENTE': this.getNodeParameter('ambiente', i) as string,
		'BIOMETRIA_FACE': this.getNodeParameter('biometriaFace', i) as string,
		'SITUACAO_CPF': this.getNodeParameter('situacaoCpf', i) as string,
		'DATA_NASCIMENTO': this.getNodeParameter('dataNascimento', i) as string,
		'CNH_POSSUI_IMPEDIMENTO': this.getNodeParameter('cnhPossuiImpedimento', i) as string,
		'CNH_CODIGO_SITUACAO': this.getNodeParameter('cnhCodigoSituacao', i) as string,
		'CNH_DATA_ULTIMA_EMISSAO': this.getNodeParameter('cnhDataUltimaEmissao', i) as string,
		'CNH_REGISTRO_NACIONAL_ESTRANGEIRO': this.getNodeParameter('cnhRegistroNacionalEstrangeiro', i) as string,
		'CNH_DATA_VALIDADE': this.getNodeParameter('cnhDataValidade', i) as string,
		'CNH_DATA_PRIMEIRA_HABILITACAO': this.getNodeParameter('cnhDataPrimeiraHabilitacao', i) as string,
		'CNH_NUMERO_REGISTRO': this.getNodeParameter('cnhNumeroRegistro', i) as string,
		'CNH_OBSERVACOES': this.getNodeParameter('cnhObservacoes', i) as string,
		'CNH_CATEGORIA': this.getNodeParameter('cnhCategoria', i) as string,
		'ENDERECO_UF': this.getNodeParameter('enderecoUf', i) as string,
		'ENDERECO_MUNICIPIO': this.getNodeParameter('enderecoMunicipio', i) as string,
		'ENDERECO_CEP': this.getNodeParameter('enderecoCep', i) as string,
		'ENDERECO_BAIRRO': this.getNodeParameter('enderecoBairro', i) as string,
		'ENDERECO_COMPLEMENTO': this.getNodeParameter('enderecoComplemento', i) as string,
		'ENDERECO_NUMERO': this.getNodeParameter('enderecoNumero', i) as string,
		'ENDERECO_LOGRADOURO': this.getNodeParameter('enderecoLogradouro', i) as string,
		'DOCUMENTO_UF_EXPEDIDOR': this.getNodeParameter('documentoUfExpedidor', i) as string,
		'DOCUMENTO_ORGAO_EXPEDIDOR': this.getNodeParameter('documentoOrgaoExpedidor', i) as string,
		'DOCUMENTO_NUMERO': this.getNodeParameter('documentoNumero', i) as string,
		'DOCUMENTO_TIPO': this.getNodeParameter('documentoTipo', i) as string,
		'FILIACAO_NOME_PAI': this.getNodeParameter('filiacaoNomePai', i) as string,
		'FILIACAO_NOME_MAE': this.getNodeParameter('filiacaoNomeMae', i) as string,
		'SEXO': this.getNodeParameter('sexo', i) as string,
		'NOME': this.getNodeParameter('nome', i) as string,
		'CPF': this.getNodeParameter('cpf', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'serpro_dv_face_tarifado',
		parametros,
		webhookUrl,
	});
}
