/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
	},
	{
			displayName: 'CVC PJ 1 RAZAO Social',
			name: 'cvcPj1RazaoSocial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 NOME Fantasia',
			name: 'cvcPj1NomeFantasia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Qualif SOCIO 2',
			name: 'qualifSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Faturamento ANUAL',
			name: 'cvcPj1FaturamentoAnual',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Patrimonio Liquido',
			name: 'cvcPj1PatrimonioLiquido',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Patrimonio Liquido',
			name: 'patrimonioLiquido',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Faturamento ANUAL',
			name: 'faturamentoAnual',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 Valida Socios',
			name: 'cvcPj2ValidaSocios',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 QTD Socios',
			name: 'cvcPj2QtdSocios',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 Qualif LEGAL REP SOCIO 2',
			name: 'cvcPj2QualifLegalRepSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 NOME Representante 2',
			name: 'cvcPj2NomeRepresentante2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 Qualif SOCIO 2',
			name: 'cvcPj2QualifSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 NOME SOCIO 2',
			name: 'cvcPj2NomeSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 Qualif LEGAL REP SOCIO 1',
			name: 'cvcPj2QualifLegalRepSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 NOME Representante 1',
			name: 'cvcPj2NomeRepresentante1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 Qualif SOCIO 1',
			name: 'cvcPj2QualifSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 NOME SOCIO 1',
			name: 'cvcPj2NomeSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 CAP Social',
			name: 'cvcPj2CapSocial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 EMAIL',
			name: 'cvcPj2Email',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 Telefone NUMERO',
			name: 'cvcPj2TelefoneNumero',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 Telefone DDD',
			name: 'cvcPj2TelefoneDdd',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 NUM Endereco',
			name: 'cvcPj2NumEndereco',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 UF Endereco',
			name: 'cvcPj2UfEndereco',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 CEP',
			name: 'cvcPj2Cep',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 DESC NAT JUR',
			name: 'cvcPj2DescNatJur',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 COD NAT JUR',
			name: 'cvcPj2CodNatJur',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 QTD CNAE Secundaria',
			name: 'cvcPj2QtdCnaeSecundaria',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 DESC CNAE SEC 1',
			name: 'cvcPj2DescCnaeSec1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 COD CNAE SEC 1',
			name: 'cvcPj2CodCnaeSec1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 DESC CNAE',
			name: 'cvcPj2DescCnae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 COD CNAE',
			name: 'cvcPj2CodCnae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 NOME Fantasia',
			name: 'cvcPj2NomeFantasia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 RAZAO Social',
			name: 'cvcPj2RazaoSocial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 DT Abertura',
			name: 'cvcPj2DtAbertura',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 2 CNPJ',
			name: 'cvcPj2Cnpj',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Valida Socios',
			name: 'cvcPj1ValidaSocios',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 QTD Socios',
			name: 'cvcPj1QtdSocios',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Qualif LEGAL REP SOCIO 2',
			name: 'cvcPj1QualifLegalRepSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 NOME Representante 2',
			name: 'cvcPj1NomeRepresentante2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Qualif SOCIO 2',
			name: 'cvcPj1QualifSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 NOME SOCIO 2',
			name: 'cvcPj1NomeSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Qualif LEGAL REP SOCIO 1',
			name: 'cvcPj1QualifLegalRepSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 NOME Representante 1',
			name: 'cvcPj1NomeRepresentante1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Qualif SOCIO 1',
			name: 'cvcPj1QualifSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 NOME SOCIO 1',
			name: 'cvcPj1NomeSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 CAP Social',
			name: 'cvcPj1CapSocial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 EMAIL',
			name: 'cvcPj1Email',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Telefone NUMERO',
			name: 'cvcPj1TelefoneNumero',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 Telefone DDD',
			name: 'cvcPj1TelefoneDdd',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 NUM Endereco',
			name: 'cvcPj1NumEndereco',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 UF Endereco',
			name: 'cvcPj1UfEndereco',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 CEP',
			name: 'cvcPj1Cep',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 DESC NAT JUR',
			name: 'cvcPj1DescNatJur',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 COD NAT JUR',
			name: 'cvcPj1CodNatJur',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 QTD CNAE Secundaria',
			name: 'cvcPj1QtdCnaeSecundaria',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 DESC CNAE SEC 1',
			name: 'cvcPj1DescCnaeSec1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 COD CNAE SEC 1',
			name: 'cvcPj1CodCnaeSec1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 DESC CNAE',
			name: 'cvcPj1DescCnae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 COD CNAE',
			name: 'cvcPj1CodCnae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Novavida Cliente',
			name: 'novavidaCliente',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CNPJ',
			name: 'cnpj',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
			required: true,
		},
	{
			displayName: 'DT Abertura',
			name: 'dtAbertura',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'RAZAO Social',
			name: 'razaoSocial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'NOME Fantasia',
			name: 'nomeFantasia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'COD CNAE',
			name: 'codCnae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'DESC CNAE',
			name: 'descCnae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'COD CNAE SEC 1',
			name: 'codCnaeSec1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'DESC CNAE SEC 1',
			name: 'descCnaeSec1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'COD CNAE SEC 2',
			name: 'codCnaeSec2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'DESC CNAE SEC 2',
			name: 'descCnaeSec2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'QTD CNAE Secundaria',
			name: 'qtdCnaeSecundaria',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'COD NAT JUR',
			name: 'codNatJur',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'DESC NAT JUR',
			name: 'descNatJur',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CEP',
			name: 'cep',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'UF Endereco',
			name: 'ufEndereco',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'NUM Endereco',
			name: 'numEndereco',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Telefone DDD',
			name: 'telefoneDdd',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'EMAIL',
			name: 'email',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
			placeholder: 'name@email.com',
		},
	{
			displayName: 'CAP Social',
			name: 'capSocial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'NOME SOCIO 1',
			name: 'nomeSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Qualif SOCIO 1',
			name: 'qualifSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'NOME Representante 1',
			name: 'nomeRepresentante1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Qualif LEGAL REP SOCIO 1',
			name: 'qualifLegalRepSocio1',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'NOME SOCIO 2',
			name: 'nomeSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'NOME Representante 2',
			name: 'nomeRepresentante2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Qualif LEGAL REP SOCIO 2',
			name: 'qualifLegalRepSocio2',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Telefone NUMERO',
			name: 'telefoneNumero',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'QTD Socios',
			name: 'qtdSocios',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Valida Socios',
			name: 'validaSocios',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'BUSCA CVC Socios',
			name: 'buscaCvcSocios',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'QTD Socios CVC PJ',
			name: 'qtdSociosCvcPj',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'Unitfour Cliente',
			name: 'unitfourCliente',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 CNPJ',
			name: 'cvcPj1Cnpj',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
	{
			displayName: 'CVC PJ 1 DT Abertura',
			name: 'cvcPj1DtAbertura',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pj'] } },
		},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = (this.getNodeParameter('webhookUrl', i) as string);
	const parametros: IDataObject = {
		'CVC_PJ_1_RAZAO_SOCIAL': this.getNodeParameter('cvcPj1RazaoSocial', i) as string,
		'CVC_PJ_1_NOME_FANTASIA': this.getNodeParameter('cvcPj1NomeFantasia', i) as string,
		'QUALIF_SOCIO_2': this.getNodeParameter('qualifSocio2', i) as string,
		'CVC_PJ_1_FATURAMENTO_ANUAL': this.getNodeParameter('cvcPj1FaturamentoAnual', i) as string,
		'CVC_PJ_1_PATRIMONIO_LIQUIDO': this.getNodeParameter('cvcPj1PatrimonioLiquido', i) as string,
		'PATRIMONIO_LIQUIDO': this.getNodeParameter('patrimonioLiquido', i) as string,
		'FATURAMENTO_ANUAL': this.getNodeParameter('faturamentoAnual', i) as string,
		'CVC_PJ_2_VALIDA_SOCIOS': this.getNodeParameter('cvcPj2ValidaSocios', i) as string,
		'CVC_PJ_2_QTD_SOCIOS': this.getNodeParameter('cvcPj2QtdSocios', i) as string,
		'CVC_PJ_2_QUALIF_LEGAL_REP_SOCIO_2': this.getNodeParameter('cvcPj2QualifLegalRepSocio2', i) as string,
		'CVC_PJ_2_NOME_REPRESENTANTE_2': this.getNodeParameter('cvcPj2NomeRepresentante2', i) as string,
		'CVC_PJ_2_QUALIF_SOCIO_2': this.getNodeParameter('cvcPj2QualifSocio2', i) as string,
		'CVC_PJ_2_NOME_SOCIO_2': this.getNodeParameter('cvcPj2NomeSocio2', i) as string,
		'CVC_PJ_2_QUALIF_LEGAL_REP_SOCIO_1': this.getNodeParameter('cvcPj2QualifLegalRepSocio1', i) as string,
		'CVC_PJ_2_NOME_REPRESENTANTE_1': this.getNodeParameter('cvcPj2NomeRepresentante1', i) as string,
		'CVC_PJ_2_QUALIF_SOCIO_1': this.getNodeParameter('cvcPj2QualifSocio1', i) as string,
		'CVC_PJ_2_NOME_SOCIO_1': this.getNodeParameter('cvcPj2NomeSocio1', i) as string,
		'CVC_PJ_2_CAP_SOCIAL': this.getNodeParameter('cvcPj2CapSocial', i) as string,
		'CVC_PJ_2_EMAIL': this.getNodeParameter('cvcPj2Email', i) as string,
		'CVC_PJ_2_TELEFONE_NUMERO': this.getNodeParameter('cvcPj2TelefoneNumero', i) as string,
		'CVC_PJ_2_TELEFONE_DDD': this.getNodeParameter('cvcPj2TelefoneDdd', i) as string,
		'CVC_PJ_2_NUM_ENDERECO': this.getNodeParameter('cvcPj2NumEndereco', i) as string,
		'CVC_PJ_2_UF_ENDERECO': this.getNodeParameter('cvcPj2UfEndereco', i) as string,
		'CVC_PJ_2_CEP': this.getNodeParameter('cvcPj2Cep', i) as string,
		'CVC_PJ_2_DESC_NAT_JUR': this.getNodeParameter('cvcPj2DescNatJur', i) as string,
		'CVC_PJ_2_COD_NAT_JUR': this.getNodeParameter('cvcPj2CodNatJur', i) as string,
		'CVC_PJ_2_QTD_CNAE_SECUNDARIA': this.getNodeParameter('cvcPj2QtdCnaeSecundaria', i) as string,
		'CVC_PJ_2_DESC_CNAE_SEC_1': this.getNodeParameter('cvcPj2DescCnaeSec1', i) as string,
		'CVC_PJ_2_COD_CNAE_SEC_1': this.getNodeParameter('cvcPj2CodCnaeSec1', i) as string,
		'CVC_PJ_2_DESC_CNAE': this.getNodeParameter('cvcPj2DescCnae', i) as string,
		'CVC_PJ_2_COD_CNAE': this.getNodeParameter('cvcPj2CodCnae', i) as string,
		'CVC_PJ_2_NOME_FANTASIA': this.getNodeParameter('cvcPj2NomeFantasia', i) as string,
		'CVC_PJ_2_RAZAO_SOCIAL': this.getNodeParameter('cvcPj2RazaoSocial', i) as string,
		'CVC_PJ_2_DT_ABERTURA': this.getNodeParameter('cvcPj2DtAbertura', i) as string,
		'CVC_PJ_2_CNPJ': this.getNodeParameter('cvcPj2Cnpj', i) as string,
		'CVC_PJ_1_VALIDA_SOCIOS': this.getNodeParameter('cvcPj1ValidaSocios', i) as string,
		'CVC_PJ_1_QTD_SOCIOS': this.getNodeParameter('cvcPj1QtdSocios', i) as string,
		'CVC_PJ_1_QUALIF_LEGAL_REP_SOCIO_2': this.getNodeParameter('cvcPj1QualifLegalRepSocio2', i) as string,
		'CVC_PJ_1_NOME_REPRESENTANTE_2': this.getNodeParameter('cvcPj1NomeRepresentante2', i) as string,
		'CVC_PJ_1_QUALIF_SOCIO_2': this.getNodeParameter('cvcPj1QualifSocio2', i) as string,
		'CVC_PJ_1_NOME_SOCIO_2': this.getNodeParameter('cvcPj1NomeSocio2', i) as string,
		'CVC_PJ_1_QUALIF_LEGAL_REP_SOCIO_1': this.getNodeParameter('cvcPj1QualifLegalRepSocio1', i) as string,
		'CVC_PJ_1_NOME_REPRESENTANTE_1': this.getNodeParameter('cvcPj1NomeRepresentante1', i) as string,
		'CVC_PJ_1_QUALIF_SOCIO_1': this.getNodeParameter('cvcPj1QualifSocio1', i) as string,
		'CVC_PJ_1_NOME_SOCIO_1': this.getNodeParameter('cvcPj1NomeSocio1', i) as string,
		'CVC_PJ_1_CAP_SOCIAL': this.getNodeParameter('cvcPj1CapSocial', i) as string,
		'CVC_PJ_1_EMAIL': this.getNodeParameter('cvcPj1Email', i) as string,
		'CVC_PJ_1_TELEFONE_NUMERO': this.getNodeParameter('cvcPj1TelefoneNumero', i) as string,
		'CVC_PJ_1_TELEFONE_DDD': this.getNodeParameter('cvcPj1TelefoneDdd', i) as string,
		'CVC_PJ_1_NUM_ENDERECO': this.getNodeParameter('cvcPj1NumEndereco', i) as string,
		'CVC_PJ_1_UF_ENDERECO': this.getNodeParameter('cvcPj1UfEndereco', i) as string,
		'CVC_PJ_1_CEP': this.getNodeParameter('cvcPj1Cep', i) as string,
		'CVC_PJ_1_DESC_NAT_JUR': this.getNodeParameter('cvcPj1DescNatJur', i) as string,
		'CVC_PJ_1_COD_NAT_JUR': this.getNodeParameter('cvcPj1CodNatJur', i) as string,
		'CVC_PJ_1_QTD_CNAE_SECUNDARIA': this.getNodeParameter('cvcPj1QtdCnaeSecundaria', i) as string,
		'CVC_PJ_1_DESC_CNAE_SEC_1': this.getNodeParameter('cvcPj1DescCnaeSec1', i) as string,
		'CVC_PJ_1_COD_CNAE_SEC_1': this.getNodeParameter('cvcPj1CodCnaeSec1', i) as string,
		'CVC_PJ_1_DESC_CNAE': this.getNodeParameter('cvcPj1DescCnae', i) as string,
		'CVC_PJ_1_COD_CNAE': this.getNodeParameter('cvcPj1CodCnae', i) as string,
		'NOVAVIDA_CLIENTE': this.getNodeParameter('novavidaCliente', i) as string,
		'CNPJ': this.getNodeParameter('cnpj', i) as string,
		'DT_ABERTURA': this.getNodeParameter('dtAbertura', i) as string,
		'RAZAO_SOCIAL': this.getNodeParameter('razaoSocial', i) as string,
		'NOME_FANTASIA': this.getNodeParameter('nomeFantasia', i) as string,
		'COD_CNAE': this.getNodeParameter('codCnae', i) as string,
		'DESC_CNAE': this.getNodeParameter('descCnae', i) as string,
		'COD_CNAE_SEC_1': this.getNodeParameter('codCnaeSec1', i) as string,
		'DESC_CNAE_SEC_1': this.getNodeParameter('descCnaeSec1', i) as string,
		'COD_CNAE_SEC_2': this.getNodeParameter('codCnaeSec2', i) as string,
		'DESC_CNAE_SEC_2': this.getNodeParameter('descCnaeSec2', i) as string,
		'QTD_CNAE_SECUNDARIA': this.getNodeParameter('qtdCnaeSecundaria', i) as string,
		'COD_NAT_JUR': this.getNodeParameter('codNatJur', i) as string,
		'DESC_NAT_JUR': this.getNodeParameter('descNatJur', i) as string,
		'CEP': this.getNodeParameter('cep', i) as string,
		'UF_ENDERECO': this.getNodeParameter('ufEndereco', i) as string,
		'NUM_ENDERECO': this.getNodeParameter('numEndereco', i) as string,
		'TELEFONE_DDD': this.getNodeParameter('telefoneDdd', i) as string,
		'EMAIL': this.getNodeParameter('email', i) as string,
		'CAP_SOCIAL': this.getNodeParameter('capSocial', i) as string,
		'NOME_SOCIO_1': this.getNodeParameter('nomeSocio1', i) as string,
		'QUALIF_SOCIO_1': this.getNodeParameter('qualifSocio1', i) as string,
		'NOME_REPRESENTANTE_1': this.getNodeParameter('nomeRepresentante1', i) as string,
		'QUALIF_LEGAL_REP_SOCIO_1': this.getNodeParameter('qualifLegalRepSocio1', i) as string,
		'NOME_SOCIO_2': this.getNodeParameter('nomeSocio2', i) as string,
		'NOME_REPRESENTANTE_2': this.getNodeParameter('nomeRepresentante2', i) as string,
		'QUALIF_LEGAL_REP_SOCIO_2': this.getNodeParameter('qualifLegalRepSocio2', i) as string,
		'TELEFONE_NUMERO': this.getNodeParameter('telefoneNumero', i) as string,
		'QTD_SOCIOS': this.getNodeParameter('qtdSocios', i) as string,
		'VALIDA_SOCIOS': this.getNodeParameter('validaSocios', i) as string,
		'BUSCA_CVC_SOCIOS': this.getNodeParameter('buscaCvcSocios', i) as string,
		'QTD_SOCIOS_CVC_PJ': this.getNodeParameter('qtdSociosCvcPj', i) as string,
		'UNITFOUR_CLIENTE': this.getNodeParameter('unitfourCliente', i) as string,
		'CVC_PJ_1_CNPJ': this.getNodeParameter('cvcPj1Cnpj', i) as string,
		'CVC_PJ_1_DT_ABERTURA': this.getNodeParameter('cvcPj1DtAbertura', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'cvc_pj',
		parametros,
		webhookUrl,
	});
}
