/* Arquivo gerado automaticamente por scripts/factory-providers-v1.ts - não editar manualmente */

import type { IDataObject, IExecuteFunctions, INodeProperties } from 'n8n-workflow';

import { webhookUrlDescription } from '../../descriptions/common.description';
import { rocketApiRequest } from '../../transport';

export const properties: INodeProperties[] = [
	{
		...webhookUrlDescription,
		displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
	},
	{
			displayName: 'Usuário de Acesso Ao Provedor',
			name: 'usuario',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
			required: true,
		},
	{
			displayName: 'Senha de Acesso Ao Provedor',
			name: 'senha',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
			typeOptions: { password: true },
			required: true,
		},
	{
			displayName: 'Codigo RJ',
			name: 'codigoRj',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Telefone Comercial',
			name: 'telefoneComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Logradouro Comercial',
			name: 'logradouroComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DATA de Nascimento Conjugue',
			name: 'dataDeNascimentoConjugue',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DATA Validade CNH',
			name: 'dataValidadeCnh',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Estado CIVIL',
			name: 'estadoCivil',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Nacionalidade',
			name: 'nacionalidade',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Naturalidade',
			name: 'naturalidade',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Logradouro Residencia',
			name: 'logradouroResidencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'NOME MAE',
			name: 'nomeMae',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'IP',
			name: 'ip',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'CPF',
			name: 'cpf',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
			required: true,
		},
	{
			displayName: 'Codigo da Agencia',
			name: 'codigoDaAgencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Codigo do BANCO',
			name: 'codigoDoBanco',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DATA de Expedicao RG',
			name: 'dataDeExpedicaoRg',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Complemento Residencia',
			name: 'complementoResidencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Complemento Comercial',
			name: 'complementoComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Bairro Residencia',
			name: 'bairroResidencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'NOME',
			name: 'nome',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
			required: true,
		},
	{
			displayName: 'Bairro Comercial',
			name: 'bairroComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DDD Telefone Comercial',
			name: 'dddTelefoneComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'NUMERO Residencia',
			name: 'numeroResidencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Numeroregistro',
			name: 'numeroregistro',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Numeroseguranca',
			name: 'numeroseguranca',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'ORGAO RG',
			name: 'orgaoRg',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'NOME PAI',
			name: 'nomePai',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'NUMERO Comercial',
			name: 'numeroComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Origem RG RS',
			name: 'origemRgRs',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Origem2 RG RS',
			name: 'origem2RgRs',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'SEXO',
			name: 'sexo',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Telefone Celular',
			name: 'telefoneCelular',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Telefone Residencial',
			name: 'telefoneResidencial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'UF Expedicao',
			name: 'ufExpedicao',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'CPF Conjugue',
			name: 'cpfConjugue',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DATA Nascimento',
			name: 'dataNascimento',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
			required: true,
		},
	{
			displayName: 'DDD Telefone Celular',
			name: 'dddTelefoneCelular',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DDD Telefone Residencial',
			name: 'dddTelefoneResidencial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Digito RG',
			name: 'digitoRg',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'EMAIL',
			name: 'email',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
			placeholder: 'name@email.com',
		},
	{
			displayName: 'Estado Comercial',
			name: 'estadoComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Estado Residencia',
			name: 'estadoResidencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DATA de Emissao CNH',
			name: 'dataDeEmissaoCnh',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'DADOS Complementares',
			name: 'dadosComplementares',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'RENDA',
			name: 'renda',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Cidade Residencia',
			name: 'cidadeResidencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'RG',
			name: 'rg',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'TIPO Contigencia Receita',
			name: 'tipoContigenciaReceita',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Cidade Comercial',
			name: 'cidadeComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'CEP Residencia',
			name: 'cepResidencia',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'CEP Comercial',
			name: 'cepComercial',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'TIPO Receita',
			name: 'tipoReceita',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'VALOR do Patrimonio',
			name: 'valorDoPatrimonio',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Profissao',
			name: 'profissao',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'NOME do Empregador',
			name: 'nomeDoEmpregador',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'NOME do Conjugue',
			name: 'nomeDoConjugue',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
	{
			displayName: 'Natureza de Ocupacao',
			name: 'naturezaDeOcupacao',
			type: 'string',
			default: '',
			displayOptions: { show: { resource: ['cm_software'], operation: ['cvc_pf'] } },
		},
];

export const description = properties;

export async function execute(this: IExecuteFunctions, i: number) {
	const webhookUrl = (this.getNodeParameter('webhookUrl', i) as string);
	const parametros: IDataObject = {
		'usuario': this.getNodeParameter('usuario', i) as string,
		'senha': this.getNodeParameter('senha', i) as string,
		'CODIGO_RJ': this.getNodeParameter('codigoRj', i) as string,
		'TELEFONE_COMERCIAL': this.getNodeParameter('telefoneComercial', i) as string,
		'LOGRADOURO_COMERCIAL': this.getNodeParameter('logradouroComercial', i) as string,
		'DATA_DE_NASCIMENTO_CONJUGUE': this.getNodeParameter('dataDeNascimentoConjugue', i) as string,
		'DATA_VALIDADE_CNH': this.getNodeParameter('dataValidadeCnh', i) as string,
		'ESTADO_CIVIL': this.getNodeParameter('estadoCivil', i) as string,
		'NACIONALIDADE': this.getNodeParameter('nacionalidade', i) as string,
		'NATURALIDADE': this.getNodeParameter('naturalidade', i) as string,
		'LOGRADOURO_RESIDENCIA': this.getNodeParameter('logradouroResidencia', i) as string,
		'NOME_MAE': this.getNodeParameter('nomeMae', i) as string,
		'IP': this.getNodeParameter('ip', i) as string,
		'CPF': this.getNodeParameter('cpf', i) as string,
		'CODIGO_DA_AGENCIA': this.getNodeParameter('codigoDaAgencia', i) as string,
		'CODIGO_DO_BANCO': this.getNodeParameter('codigoDoBanco', i) as string,
		'DATA_DE_EXPEDICAO_RG': this.getNodeParameter('dataDeExpedicaoRg', i) as string,
		'COMPLEMENTO_RESIDENCIA': this.getNodeParameter('complementoResidencia', i) as string,
		'COMPLEMENTO_COMERCIAL': this.getNodeParameter('complementoComercial', i) as string,
		'BAIRRO_RESIDENCIA': this.getNodeParameter('bairroResidencia', i) as string,
		'NOME': this.getNodeParameter('nome', i) as string,
		'BAIRRO_COMERCIAL': this.getNodeParameter('bairroComercial', i) as string,
		'DDD_TELEFONE_COMERCIAL': this.getNodeParameter('dddTelefoneComercial', i) as string,
		'NUMERO_RESIDENCIA': this.getNodeParameter('numeroResidencia', i) as string,
		'NUMEROREGISTRO': this.getNodeParameter('numeroregistro', i) as string,
		'NUMEROSEGURANCA': this.getNodeParameter('numeroseguranca', i) as string,
		'ORGAO_RG': this.getNodeParameter('orgaoRg', i) as string,
		'NOME_PAI': this.getNodeParameter('nomePai', i) as string,
		'NUMERO_COMERCIAL': this.getNodeParameter('numeroComercial', i) as string,
		'ORIGEM_RG_RS': this.getNodeParameter('origemRgRs', i) as string,
		'ORIGEM2_RG_RS': this.getNodeParameter('origem2RgRs', i) as string,
		'SEXO': this.getNodeParameter('sexo', i) as string,
		'TELEFONE_CELULAR': this.getNodeParameter('telefoneCelular', i) as string,
		'TELEFONE_RESIDENCIAL': this.getNodeParameter('telefoneResidencial', i) as string,
		'UF_EXPEDICAO': this.getNodeParameter('ufExpedicao', i) as string,
		'CPF_CONJUGUE': this.getNodeParameter('cpfConjugue', i) as string,
		'DATA_NASCIMENTO': this.getNodeParameter('dataNascimento', i) as string,
		'DDD_TELEFONE_CELULAR': this.getNodeParameter('dddTelefoneCelular', i) as string,
		'DDD_TELEFONE_RESIDENCIAL': this.getNodeParameter('dddTelefoneResidencial', i) as string,
		'DIGITO_RG': this.getNodeParameter('digitoRg', i) as string,
		'EMAIL': this.getNodeParameter('email', i) as string,
		'ESTADO_COMERCIAL': this.getNodeParameter('estadoComercial', i) as string,
		'ESTADO_RESIDENCIA': this.getNodeParameter('estadoResidencia', i) as string,
		'DATA_DE_EMISSAO_CNH': this.getNodeParameter('dataDeEmissaoCnh', i) as string,
		'DADOS_COMPLEMENTARES': this.getNodeParameter('dadosComplementares', i) as string,
		'RENDA': this.getNodeParameter('renda', i) as string,
		'CIDADE_RESIDENCIA': this.getNodeParameter('cidadeResidencia', i) as string,
		'RG': this.getNodeParameter('rg', i) as string,
		'TIPO_CONTIGENCIA_RECEITA': this.getNodeParameter('tipoContigenciaReceita', i) as string,
		'CIDADE_COMERCIAL': this.getNodeParameter('cidadeComercial', i) as string,
		'CEP_RESIDENCIA': this.getNodeParameter('cepResidencia', i) as string,
		'CEP_COMERCIAL': this.getNodeParameter('cepComercial', i) as string,
		'TIPO_RECEITA': this.getNodeParameter('tipoReceita', i) as string,
		'VALOR_DO_PATRIMONIO': this.getNodeParameter('valorDoPatrimonio', i) as string,
		'PROFISSAO': this.getNodeParameter('profissao', i) as string,
		'NOME_DO_EMPREGADOR': this.getNodeParameter('nomeDoEmpregador', i) as string,
		'NOME_DO_CONJUGUE': this.getNodeParameter('nomeDoConjugue', i) as string,
		'NATUREZA_DE_OCUPACAO': this.getNodeParameter('naturezaDeOcupacao', i) as string,
	};

	return await rocketApiRequest.call(this, 'POST', '', {
		origem_solic: 'N8N',
		provider: 'cvc_pf',
		parametros,
		webhookUrl,
	});
}
